# Numpy

In machine learning, we have lots and lots of data which creates problems when we use python lists which are computationally expensive as they can store different type of data types in a list and they are computationally slow.

So, we use numpy arrays in machine learning which is just a list but its different !

Lets import numpy - numeric python

## Importing Numpy

In [2]:
import numpy as np

Anything in numpy array shuld be of same datatype.

ndarray = n-dimensinal array.

lets create a numpy array.

## Basics of Numpy

In [3]:
np1 = np.array([1,2,3,4,5])
print(np1)

[1 2 3 4 5]


They are basically list, but are lot more powerful, has many mathematical functions!.

In [5]:
print(np1.shape)

(5,)


In [6]:
# get a list of numbers :
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# step arrangement
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


In [8]:
# array of zeroes.
np4 = np.zeros(5)
print(np4)

[0. 0. 0. 0. 0.]


In [17]:
# multidimensional zeroes
np1 = np.zeros((2,5))
print(np1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Full function
np1 = np.full(10, 6)
print(np1)

[6 6 6 6 6 6 6 6 6 6]


In [20]:
#multidimensional full
np1 = np.full((2,5), 6)
print(np1)

[[6 6 6 6 6]
 [6 6 6 6 6]]


In [21]:
# Converting python lists to numpy array
list1 = [1,2,3,4,5]
np1 = np.array(list1)
print(np1,list1)

[1 2 3 4 5] [1, 2, 3, 4, 5]


## Random arrays in Numpy

In [133]:
# Random numbers between 0 & 1
np1 = np.random.rand(2,5)
print(np1)

[[0.72718725 0.44119662 0.1750741  0.17753798 0.11858355]
 [0.77516745 0.83261357 0.58070049 0.06708852 0.61316523]]


In [134]:
# random numbers close to 0
np1 = np.random.randn(2,5)
print(np1)

[[ 1.35829093 -0.38516022  0.18560283  1.39486216  0.24575653]
 [ 0.973274   -0.45354929  0.47897977  0.22829871 -0.13356848]]


In [136]:
# random integers between range (5-20)
np1 = np.random.randint(5,20,6)
print(np1)

[ 6  7 15 18  8 10]


## Slicing in numpy arrays

In [22]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1)

[1 2 3 4 5 6 7 8 9]


In [23]:
# what if we want to return 2 3 4 5
print(np1[1:5])

[2 3 4 5]


In [24]:
# till the end
print(np1[3:])

[4 5 6 7 8 9]


In [25]:
# from the end
print(np1[-3:-1])

[7 8]


In [26]:
# Slices with steps
print(np1[1:5:2])

[2 4]


In [28]:
#print entire with steps
print(np1[::2])
print(np1[::3])

[1 3 5 7 9]
[1 4 7]


In [34]:
#Slicing in multidimensional array
np2 = np.array([np.arange(1,6), np.arange(6,11)])
print(np2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# pulling out single item 
print(np2[1,2])

# pulling slices from 2d array
print(np2[0:1, 1:3])

# and 
print(np2[:,1:3]) # or np2[0:2,1:3]

8
[[2 3]]
[[2 3]
 [7 8]]


## Numpy Universal Functions

In [41]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
#Square root of each element
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [44]:
#absolute value 
#modulus value in other words
print(np.absolute(np1))

[0 1 2 3 4 5 6 7 8 9]


In [45]:
# exponents
print(np.exp(np1))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [47]:
# Min/Max
print(np.max(np1))
print(np.min(np1))

9
0


In [49]:
# Sign positive or negative
print(np.sign(np1))
# all are positive in our case.

[0 1 1 1 1 1 1 1 1 1]


In [51]:
# Trig functions
print(np.sin(np1))
print(np.log(np1[1:]))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


You can go through the docs for more mathematical functions:
[Official Docs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)

## Copy Vs View

In [52]:
np1 = np.arange(6)
print(np1)

[0 1 2 3 4 5]


In [54]:
# create a view
np2 = np1.view()
# like a shallow copy both of them points to the same address.
print(np2)
np1[0] = 10
print(np2)

[0 1 2 3 4 5]
[10  1  2  3  4  5]


In [55]:
np1[0] = 0

In [67]:
# Create a Copy
np2 = np1.copy()
# Deep copy which creates a entire new array with new address but the same data.
print(np2)
np1[0] = 10
print(np2)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [68]:
np1[0] = 0

## Shape & Reshape

In [72]:
# getting shape of 1D array
np1 = np.arange(1,13)
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [73]:
# 2D array
np2 = np.array([np.arange(1,7),np.arange(7,13)])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [89]:
# Reshaping 1D to 2D
np3 = np1.reshape(3,-1)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [90]:
# flatten to 1D
np4 = np3.reshape(-1)
print(np4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Iterating through numpy arrays

In [98]:
np1 = np.arange(1,28)
np1 = np1.reshape(3,3,-1)
print(np1)
print(np1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)


In [99]:
#It gets tough to write loops if we have multiple dimensions
# Use numpy.nditer()

for x in np.nditer(np1):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


## Sorting numpy arrays

In [100]:
# sorting based on certain numerical values
np1 = np.array([6,7,4,8,10,2,9])
print(np1)

[ 6  7  4  8 10  2  9]


In [105]:
print(np.sort(np1))

[ 2  4  6  7  8  9 10]


In [113]:
np2 = np.array([[6,3,7,9,7,2],[1,5,3,6,3,9]])
print(np2)

[[6 3 7 9 7 2]
 [1 5 3 6 3 9]]


In [114]:
print(np.sort(np2))

[[2 3 6 7 7 9]
 [1 3 3 5 6 9]]


## Searching numpy arrays

In [124]:
np1 = np.arange(1,11)
print(np1)

[ 1  2  3  4  5  6  7  8  9 10]


In [125]:
x = np.where(np1 == 3)
print(np1)
print(x)


[ 1  2  3  4  5  6  7  8  9 10]
(array([2]),)


In [126]:
print(x[0])
# array of positions where np1 == 3.

[2]


In [129]:
# even items
x = np.where(np1%2==0)
print(x[0])

[1 3 5 7 9]


## Filter Numpy arrays

In [130]:
np1 = np.arange(1,6)
print(np1)

[1 2 3 4 5]


In [131]:
x = [True, True,False,False,False]
print(np1[x])

[1 2]


In [132]:
filter = np1 % 2 ==0
print(np1[filter])

[2 4]
